// bnf grammar for language
statement: term ASSIGNMENT expr; 

// expression
expr: term expr
    | op term 
    ;

// operands
term: name 
    | FLOAT 
    | INT 
    | STRING
    ;

name: VAR_NAME | FUNC_NAME;

// operations
op:   ADD 
    | SUBTRACT
    | MULTIPLY
    | DIVIDE
    ;