// bnf grammar for language
statement: expr ASSIGNMENT term; 

// expression
expr: expr op term
    | term op term
    ;

// operands
term: NAME 
    | FLOAT 
    | INT 
    | STRING
    ;

// operations
op:   ADD 
    | SUBTRACT
    | MULTIPLY
    | DIVIDE
    ;