// bnf grammar for language
// NOTE: uppercase words match to tokens
statement: expr assignment term
        | term assignment term
        ; 

// assignment
assignment: ASSIGNMENT;

// expression
expr: expr op term
    | term op term
    ;

// operands
term: NAME 
    | FLOAT 
    | INT 
    | STR
    | OP expr CP
    | OP term CP
    ;

// operations
op: ADD 
    | SUBTRACT
    | MULTIPLY
    | DIVIDE
    ;